config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "boxes#new"

  resources :boxes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  validates :name, presence: true
  validates :shipping_date, presence: true
  validates :shipping_time, presence: true

  validates :colors, length: { minimum:1, maximum: 2 }

  validates :material, presence: true


  belongs_to :material
  has_and_belongs_to_many :colors
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :boxes
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :boxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def new
    @box = Box.new

    #@box.valid?
  end

  def create
    @box = Box.new params[:box].permit!
    @box.valid?

    render "new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/new.html.erb
<div class="container m-5 p-5">

  <%= simple_form_for @box, url: boxes_path, validate: true do |f| %>

    <%=
      f.input :name
    %>

    <div class="row">
      <div class="col-6">
        <%=
          f.input :shipping_date, include_blank: true
        %>
      </div>
      <div class="col-6">
        <%=
          f.input :shipping_time, include_blank: true
        %>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <%=
           f.association :material, as: :radio_buttons, validate: true, wrapper: :horizontal_collection, hint: 'bla bla hint'
         %>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <%=
           f.association :colors, as: :check_boxes, wrapper: :vertical_collection, hint: 'select max 2 colors'
         %>
      </div>
    </div>

    <%= f.submit %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSVExampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>